export default {
  check: require('./img/check.png'),
  directions: require('./img/directions.png'),
  facebook: require('./img/facebook.png'),
  filter: require('./img/filter.png'),
  github: require('./img/github.png'),
  linkedin: require('./img/linkedin.png'),
  mapMarkerMultiple: require('./img/map-marker-multiple.png'),
  mapMarker: require('./img/map-marker.png'),
  restaurant: require('./img/silverware-fork-knife.png'),
  starHalf: require('./img/star-half.png'),
  starEmpty: require('./img/star-empty.png'),
  starFull: require('./img/star-full.png'),
  home: require('./img/home.png'),
  search: require('./img/search.png'),
  map: require('./img/map.png'),
  user_profile: require('./img/user_profile.png'),
  settings: require('./img/settings.png'),
};
