const CONSTANTS = {
  NAVIGATION_PARAM_IS_DISH_DETAIL_REVIEW_MODE:
    'NAVIGATION_PARAM_IS_DISH_DETAIL_REVIEW_MODE',
  NAVIGATION_PARAM_USER_LOCATION: 'NAVIGATION_PARAM_USER_LOCATION',
  NAVIGATION_PARAM_HEADER_HAS_DATA_STYLE:
    'NAVIGATION_PARAM_HEADER_HAS_DATA_STYLE',
  NAVIGATION_PARAM_HEADER_LOADING_STYLE:
    'NAVIGATION_PARAM_HEADER_LOADING_STYLE',
  NAVIGATION_PARAM_HEADER_ERROR_STYLE: 'NAVIGATION_PARAM_HEADER_ERROR_STYLE',
  NAVIGATION_PARAM_RESTAURANT_NAME: 'NAVIGATION_PARAM_RESTAURANT_NAME',
  ROUTE_RESTAURANT_ADDRESS_MAP: 'ROUTE_RESTAURANT_ADDRESS_MAP',
  ROUTE_DISH_DETAIL_REVIEW: 'ROUTE_DISH_DETAIL_REVIEW',
  ROUTE_RESTAURANT_DETAIL: 'ROUTE_RESTAURANT_DETAIL',
  NAVIGATION_PARAM_ID: 'NAVIGATION_PARAM_ID',
  ROUTE_DISH_DETAIL: 'ROUTE_DISH_DETAIL',
  USER_LOCATION: 'USER_LOCATION',
  FORTALEZA_CITY_LOCATION: {
    latitude: -3.7899266,
    longitude: -38.588988,
  },
};

export default CONSTANTS;
